sudo: false
language: elixir
elixir:
  - 1.5.0-rc.0
otp_release:
  - 20.0
env:
  - TRAVIS_NODE_VERSION="8"
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install -g yarn
  - yarn
script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix compile
  - yarn build
  - mix test
  - yarn test
  - yarn test-app
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fbd8944d285c0696dc41
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always